# (can be indices)
X, O = 0, 1

# board constants
BLOCK_WIDTH = 70
SEC_SEP_WIDTH = 3
PRM_SEP_WIDTH = 10
CONSOLE_HEIGHT = 80
SUB_WIDTH = 3 * BLOCK_WIDTH + 2 * SEC_SEP_WIDTH
SCREEN_WIDTH = 4 * PRM_SEP_WIDTH + 3 * SUB_WIDTH
SCREEN_HEIGHT = SCREEN_WIDTH + CONSOLE_HEIGHT

# start prompts
BUTTON_HEIGHT = 35
BUTTON_WIDTH = 250
PROMPT_BUTTON_SEP_WIDTH = 50